### ISSUE TITLE
Cannot Install - Multiple Approach Tried

### ISSUE THREAD

**Issue by xinyaonie** [AdeelK93/collapsibleTree#11]
I've tried multiple approach to install the package with no successful. Appreciate any help to get this amazing visualization package to work. 

**Approach 1:**
```
library('devtools')
devtools::install_github("AdeelK93/collapsibleTree")
```
> Error : object 'Sort' is not exported by 'namespace:data.tree'
> ERROR: lazy loading failed for package 'collapsibleTree'

**Approach 2**

`install.packages('collapsibleTree')`

> package ‘collapsibleTree’ is available as a source package but not as a binary
> Warning in install.packages :
>   package ‘collapsibleTree’ is not available (for R version 3.1.2)

**Approach 3**

`install.packages('collapsibleTree', dependencies=TRUE, type="source")`

> Warning in install.packages :
>   installation of package ‘collapsibleTree’ had non-zero exit status

**Comment by AdeelK93** [comment]
It's possible your data.tree package is out of date, could you try updating that and then reinstalling?

**Comment by xinyaonie** [comment]
Issue resolved by upgrading my R to the latest version

amazing package, love it!
