### ISSUE TITLE
(1) Links/Shiny Input (2) Pan & Zoom

### ISSUE THREAD

**Issue by RSchwinn** [AdeelK93/collapsibleTree#15]
Above all: Excellent work. I thank you for sharing your hard work.

(1) Links / Shiny Input
Is it already possible to trigger a shiny input variable given clicks on a terminal node's text? I'd like for users to be able to search through a tree and then, after finding the entry that interests them, to have the ability to trigger events/content associated with that node.

(2) Pan & Zoom
I want to second the other request for [http://bl.ocks.org/robschmuecker/7880033](http://bl.ocks.org/robschmuecker/7880033) style panning and zooming. I think this will be a game changer.

**Comment by AdeelK93** [comment]
1) Shiny input is definitely possible, you can see a live demo of it [here](https://adeelk93.shinyapps.io/collapsibletree/), which works by adding an `inputId` parameter and then reading from that input name

2) Pan & zoom is a great idea and something I definitely want to incorporate, I'll try to work on that soon! Right now I'm thinking this will be an toggle between either the current responsive layout or pan & zoom

**Comment by AdeelK93** [comment]
I've added some very basic pan+zoom functionality to the github version of the package (you can also check it out [here](https://adeelk93.github.io/collapsibleTree/), let me know what you think!

**Comment by RSchwinn** [comment]
I think you are a genius.
