### ISSUE TITLE
'root' argument appears to be missing.

### ISSUE THREAD

**Issue by RSchwinn** [AdeelK93/collapsibleTree#18]
One thing:
(1) Running a collapsibleTree seems to interfere with networkD3's simpleNetwork but not vice versa. Specifically the simple network nodes become white.
Thank you for your efforts!

PS: The issue is [my data](http://richschwinn.com/index/as.Node_this_list.RDS). Essentially, I have a data.tree object whose root I cannot rename. I tested with your data before posting but I must have mistyped something because it works now. Sorry.

**Comment by AdeelK93** [comment]
1) What do you mean? For which function are is the `root` argument not working? You should be able to use it like:

```r
collapsibleTree(warpbreaks, c("wool", "tension", "breaks"), root = "custom root name")
```

2) That's probably a css issue, I'll have to try out networkD3's `simpleNetwork` to see what's up with that, but it's most likely this part of my css not being namespaced properly

```css
.node circle {
  fill: #fff;
  stroke: #000;
}
```

**Comment by AdeelK93** [comment]
Fixed the css namespacing issue, `collapsibleTree` and `simpleNetwork` should now play better together!
