### ISSUE TITLE
Error with Shiny apps examples 02 03

### ISSUE THREAD

**Issue by wmatwijec** [AdeelK93/collapsibleTree#2]
Thank you for your effort on this.  I see these errors when trying the shiny apps.

> shiny::runApp(system.file("examples/02shiny", package = "collapsibleTree"))

Listening on http://127.0.0.1:5097
Warning: Error in data.tree::ToListExplicit: unused argument (keepOnly = jsonFields)
Stack trace (innermost first):

**Comment by AdeelK93** [comment]
Well that's not good! Do you know which version of data.tree you have installed? Perhaps that's out of date?

**Comment by wmatwijec** [comment]
Yes that was it. I thought so but after sending in the issue.  So I updated
from .4 to .7 and now both shiny examples are running perfectly.  Thanks
again for this awesome effort.  I can see many uses for this.

Walt

**Comment by AdeelK93** [comment]
Happy to hear, Walt! Let me know if you run into any more issues or have any suggestions!
