### ISSUE TITLE
[Feature Request] Prune/Search the tree without reloading

### ISSUE THREAD

**Issue by xfdeng2008** [AdeelK93/collapsibleTree#20]
Are we able to search the tree without reloading? 
(1) search against the whole tree, then a sub-tree is returned;
(2) search against a selected set of nodes, then a sub tree is returned;
(3) for (1) and (2) the result can be either a sub-tree or unfolding and highlighting the matched node.

**Comment by AdeelK93** [comment]
What do you mean by search the tree?

**Comment by AdeelK93** [comment]
I'm going to close this issue because I don't really understand it
