### ISSUE TITLE
collapsibleTreeNetwork: show images dynamically in tooltop

### ISSUE THREAD

**Issue by MohanBunny** [AdeelK93/collapsibleTree#23]
Hi AdeelK93,

This is an excellent package which will give lots of insights.

Can we show the images dynamically each image for each bubble.

Is it possible.

Thanks
Mohan V

**Comment by AdeelK93** [comment]
What do you mean by dynamic images? Like in the tooltips? The examples for the `collapsibleTreeNetwork` function show how to do that

**Comment by AdeelK93** [comment]
I'm going to close this issue since I haven't heard anything in months, and I'm pretty sure this is covered by `tooltipHtml`
