### ISSUE TITLE
Error in unclass(x) : cannot unclass an environment

### ISSUE THREAD

**Issue by violetzh** [AdeelK93/collapsibleTree#24]
Hi AdeelK93!

First, this is a great package and very useful to visualize hierarchical data. 

I have run into an issue when trying to generate a collapsible tree using the method collapsibleTreeNetwork, with strings (some quite long) as the attribute for each node. The error is:
_Error in unclass(x) : cannot unclass an environment_
If no attribute is assigned, then the tree will render with no error. 
Google tells me this could be a layout issue, but I am not exactly sure what it means. Would it be possible to provide some insights how to fix this?

The network data frame has 634 unique nodes.
Here is my script:
```
library(shiny)
library(collapsibleTree)
library(data.tree)

aft_tree<-read.delim("aftv212_child_parent_class_tree_fixes.tsv", stringsAsFactors = F)
#convert a data.frame in network structure to a data.tree structure
aft_tree_network<-FromDataFrameNetwork(aft_tree)

#see if all node names are unique
print(AreNamesUnique(aft_tree_network))
#convert data.tree structure back to the data.frame in network structure with column names "from" and "to" 
#order of the nodes are preserved using this method
aft_tree_df<-ToDataFrameNetwork(aft_tree_network)

aft_tree_df_for_d3<-rbind(data.frame(from=NA, to="entity", stringsAsFactors = F),aft_tree_df)
aft_tree<-rbind(data.frame(parentLabel=NA, childLabel="entity", parentURI="", childURI="<http://purl.obolibrary.org/obo/BFO_0000001>", description="An entity is anything that exists or has existed or will exist. (axiom label in BFO2 Reference: [001-001])", root="<http://purl.obolibrary.org/obo/BFO_0000001>", depth=0, stringsAsFactors = F), aft_tree)
colnames(aft_tree)<-c("from", "to", "fromIRI", "toIRI", "description", "root", "depth")
aft_tree_for_d3_wDes<-cbind(aft_tree_df_for_d3, data.frame(aft_tree$description, stringsAsFactors = F))
colnames(aft_tree_for_d3_wDes)<-c("from", "to", "description")
collapsibleTreeNetwork(aft_tree_for_d3_wDes, attribute="description", zoomable = F, linkLength = 300)
```
Thanks!
Violet

**Comment by AdeelK93** [comment]
That's a strange one, would you happen to have an example of the `aftv212_child_parent_class_tree_fixes.tsv` file?

**Comment by violetzh** [comment]
Here is an example based on the original tsv file:

**Comment by violetzh** [comment]
The tsv file was sent via email. Thanks!

**Comment by AdeelK93** [comment]
I don't think I got that email, could you send it to AdeelK@gwu.edu? Thanks

**Comment by AdeelK93** [comment]
At first I thought this might have been some collision with a data.tree reserved word, but that doesn't appear to be the case. It looks like your use of the column name "description" is causing some issue with the json mappings in htmlwidgets, though I'm not totally sure why, though this error appears to afflict other htmlwidgets in some cases.

Fortunately, it should be an easy fix! Would you be alright with replacing "description" with "Description" in your last two lines of code?

**Comment by violetzh** [comment]
Yes. That does fix the error! Thanks!
