### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by jl5000** [AdeelK93/collapsibleTree#28]
I've upgraded R and RStudio to the latest versions, and I end up getting the same error on both systems I have RStudio installed on:

> library(collapsibleTree)
Error: package or namespace load failed for ‘collapsibleTree’:
 object ‘cividis’ is not exported by 'namespace:viridisLite'

**Comment by AdeelK93** [comment]
Could you try reinstalling viridisLite?

**Comment by jl5000** [comment]
That solved it - thanks!
