### ISSUE TITLE
Varying depth

### ISSUE THREAD

**Issue by ShKlinkenberg** [AdeelK93/collapsibleTree#3]
Hi Adeel,

I'm getting errors when I try to make tree diagrams wit varying depth [My repo](https://github.com/ShKlinkenberg/assessment_tree). Is there a work around? I could not vind it in the manual.

Kind regards,
Sharon

**Comment by ShKlinkenberg** [comment]
Solved. The readxl import added NA's that gave an issue. Converting NA's to string "" solved the depth issue

**Comment by AdeelK93** [comment]
Huh! I had opted to just throw an error if a table had NA's because data.tree would throw an error, do you think this might be a better default?

**Comment by ShKlinkenberg** [comment]
The NA's are a natural result of varying depth trees. What I did now is:

`tree <- read_excel("file.xlsx")

assessment.tree[is.na(tree)] <- ""`

I think it would be good to have your widget handle this. It took me some time to figure out that this worked. 

None the less, great widget. Thanks a lot for building it!

**Comment by AdeelK93** [comment]
Sorry this took so long to get to, but I implemented your suggestion, thank you!

**Comment by ShKlinkenberg** [comment]
Cool!

Thanks

_____

Universiteit van Amsterdam

Sharon Klinkenberg

Bezoek | Nieuwe Achtergracht 129B<https://mapkit.io/embed/cq4eoa> | Kamer REC-G -1.12 (Souterrain)
Post | Postbus 15943 | 1001 NK Amsterdam
Pakketpost | Valckenierstraat 59 | 1018 XE Amsterdam
T: +31 (0)20 525 6904 | S.Klinkenberg@uva.nl
