### ISSUE TITLE
[feature requested] display tree with one line !

### ISSUE THREAD

**Issue by philibe** [AdeelK93/collapsibleTree#32]
Sometimes I have tree with only one root without children. I would like display the unique node without the errors "This is not a Tree".

My workaround is to build a 2nd node with parent id, the id of root, and its id "nothing", when there is only one root line in the tree.

**Comment by philibe** [comment]
It is about collapsibleTreeNetwork (in Shiny).

**Comment by AdeelK93** [comment]
Hmm I never considered a 1 node tree, I can look into adding a special case for that. Good catch

**Comment by AdeelK93** [comment]
Fixed in the github version, let me know if that works for you. Will push to CRAN in the next few weeks.

**Comment by philibe** [comment]
Tested quickly in my app : it works :) 
Thanks :)
