### ISSUE TITLE
Error when dataframe is too long: evaluation nested too deeply: infinite recursion / options(expressions=)?

### ISSUE THREAD

**Issue by nima-akram** [AdeelK93/collapsibleTree#33]
Hi Adeel,

First of all, this is a great package so thanks a lot for developing it.

The collapsibleTree function seemingly can't cope with dataframes that are too long, 8000 rows and 1000 steps in the hierarchy in my case. The following error is thrown:

`Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
Error during wrapup: evaluation nested too deeply: infinite recursion / options(expressions=)?`

Digging into this a little deeper, I suspect that the issue can be solved by setting the max ppsize in the command line to allow for larger dataframe processing. This isn't very seemless especially as the aim is to push my Shiny App to production. 

Is there a way around this within your package? And if not, are you aware of a work-around within R rather than the command line?

Any help is much appreciated.

Thanks,

Nima

**Comment by AdeelK93** [comment]
I see you ended up closing this issue, did you end up resolving it?
