### ISSUE TITLE
Collapse/Expand till a specific level

### ISSUE THREAD

**Issue by mangupedia** [AdeelK93/collapsibleTree#43]
Hi Adeel,

Can we parametrize/configure node level expand/collapse the tree on load?
The current "collapsed=TRUE/FALSE" does expand/collapse all.

**Comment by AdeelK93** [comment]
Hi @mangupedia, I've added this feature in the latest github version. You can now map a logical data point to the `collapsed` option to conditionally collapse the tree. Check it out and let me know what you think!

**Comment by zac-garland** [comment]
Hi @AdeelK93 could you provide an example of this? I've tried to implement this in all of the variations of collapsibletree e.g. (network, summary, collapsibletree) and have not been able to get it to work. 

a simple example that I thought would work given the commits and docs:

```
collapsibleTree(
  warpbreaks, c("wool", "tension"),
  fill = brewer.pal(9, "RdBu"),
  collapsed = c(sample(c(T,F),9,replace = T)),
  fillByLevel = FALSE
)
```
