### ISSUE TITLE
Node Size issue with collapsibleTreeNetwork

### ISSUE THREAD

**Issue by sunfengnian88** [AdeelK93/collapsibleTree#45]
dataset:
![data set](https://user-images.githubusercontent.com/23142050/48086569-3181c900-e1cb-11e8-8178-8bbb3e08b3d9.PNG)

code:
library(collapsibleTree)

df <- read.csv(file="test_data.csv", header=TRUE,sep=",", na.strings = c("", NA))

len <- nrow(df)

colfunc <- colorRampPalette(c("red", "paleturquoise1"))

color_col <- colfunc(len)

df$Color <- color_col
  
p <- collapsibleTreeNetwork(
  df,
  fill = "Color",
  attribute = "value",
  collapsed = TRUE,
  height = 800,
  width = 2000,
  zoomable = TRUE,
  aggFun = identity,
  tooltip = TRUE,
  nodeSize = "value"
)

In the plot, the size of node B is not proportional to its value 184 as screenshot below.
![plot](https://user-images.githubusercontent.com/23142050/48086743-90dfd900-e1cb-11e8-940a-2e77027eb771.PNG)

It seems like parent node size is sum aggregation of its all children size. However, what I expect is that each node size is independent based on its specified column variable.

Can you please make more clarification about this?

Thank you!

**Comment by AdeelK93** [comment]
Thanks for catching this! I've corrected this in my latest github commit, could you check it out and see if that works for you?

<img width="705" alt="screen shot 2018-11-10 at 2 52 28 pm" src="https://user-images.githubusercontent.com/16856016/48305441-69a14880-e4f8-11e8-8d13-51424d5035a8.png">

**Comment by sunfengnian88** [comment]
This is exactly what I expect. Perfect!
