### ISSUE TITLE
Load data dynamically?

### ISSUE THREAD

**Issue by danboh** [AdeelK93/collapsibleTree#46]
Hi! This looks like a great tool, so thank you!

But is there a way I could load the data dynamically instead of using a file? I'm trying to avoid the CORS issue when running the solution locally without a server.

Is this possible?

Thanks!

**Comment by AdeelK93** [comment]
CORS? On a Shiny? I’m not sure I understand your use case

**Comment by danboh** [comment]
Yes. Chrome throws out a CORS error when loading the data from a file when you run the HTML locally, without a web server. I was able to bypass this by injecting the data directly into a variable in the script section.

**Comment by AdeelK93** [comment]
What do you mean “run the HTML locally”? Like as a self-standing htmlwidget or an RMarkdown?

**Comment by danboh** [comment]
Just run the html, no server
