### ISSUE TITLE
deprecated Node$fields

### ISSUE THREAD

**Issue by bhogan-mitre** [AdeelK93/collapsibleTree#59]
The `data.tree` package is [deprecating `Node$fields` in favor of `Node$attributes`](https://github.com/gluc/data.tree/blob/master/NEWS#L7).  This is leading to a lot of warnings for users that are on the development version of `data.tree`.

```
[1] "Node$fields will be deprecated in the next release. Please use Node$attributes instead."
[1] "Node$fields will be deprecated in the next release. Please use Node$attributes instead."
[1] "Node$fields will be deprecated in the next release. Please use Node$attributes instead."
...
```

This seems like a fairly trivial adjustment is needed [here](https://github.com/AdeelK93/collapsibleTree/blob/master/R/collapsibleTree.data.tree.R#L51).  I'm happy to submit a PR if you're open to it.  Thanks for considering.

**Comment by AdeelK93** [comment]
Thanks for bringing this to my attention, I would love if you submitted a PR for this

**Comment by bhogan-mitre** [comment]
Checkin in on this one.  Let me know if you have questions on the PR or need anything else here @AdeelK93.  Thanks.

**Comment by AdeelK93** [comment]
Oh sorry I totally missed this! Merged

**Comment by bhogan-mitre** [comment]
No worries, thanks!
