### ISSUE TITLE
Feature request: Multiple attributes in tooltip

### ISSUE THREAD

**Issue by acom182** [AdeelK93/collapsibleTree#9]
I'm trying to figure out if it is possible to add additional attributes to the tooltip, pulling from additional columns in the data. Any advice on how to do this?

Just adding to this - wondering if it is possible to implement pan and zoom functionality as well, similar to that[ shown here](http://bl.ocks.org/robschmuecker/7880033) or [here (easier version)](https://stackoverflow.com/questions/17405638/d3-js-zooming-and-panning-a-collapsible-tree-diagram). I can't seem to get either working unfortunately.

**Comment by AdeelK93** [comment]
Have you tried `paste`ing the columns together, and feeding that column into the tooltip? 

Panning and zooming is a great idea, if I have some free time I'll try to look into implementing that!

**Comment by acom182** [comment]
Paste works, but wanted to see if it is possible to directly reference multiple columns in the same format as the current tooltip - i.e. with "columnname: datapoint."

Looking forward to seeing the pan and zoom. I tried a few different things with the JS file in your package but couldn't get it working unfortunately - I'm a bit too novice for these things.

Thanks for the reply!

**Comment by AdeelK93** [comment]
Hi @acom182 , sorry for not getting back to you sooner, but I've added some very basic pan+zoom functionality to the github version of the package (you can also check it out [here](https://adeelk93.github.io/collapsibleTree/), let me know what you think!

**Comment by acom182** [comment]
Thanks @AdeelK93 this is great! Appreciate the update, it works exactly as I hoped. Great work!
